Criar Endereço
TreinaDev/ecommerce-td6 pull request #30
Opened 2021-07-19 20:30 UTC by oliveira-matheus

## Motivação

Criar os endereços associados à conta de usuário

#26

2021-07-20 15:48 UTC, joaorsalmeida commented on app/controllers/user/addresses_controller.rb
> +    @addresses = Address.where(user: current_user)
O mais comum aqui é `current_user.addresses` por exemplo

2021-07-20 15:50 UTC, joaorsalmeida commented on app/controllers/user/addresses_controller.rb
> +    @address = Address.create(address_params.merge(user: current_user))
Aqui, na mesma linha do `index`, vocês podem fazer algo como:

`current_user.addresses << `

Vale a pena ver todos os métodos gerados pela associação.

2021-07-20 15:52 UTC, joaorsalmeida requested changes
Pessoal, vi que existe uma action `show` que deixa qualquer pessoa ver qualquer endereçø. Não me parece muito útil e acabou gerando uma potencial brecha de segurança. Podem revisar? Vocês podem atualizar e colocar uma verificação de segurança ou usar somente a `index` que já busca a partir do usuário atual.

2021-07-20 15:52 UTC, joaorsalmeida commented on app/controllers/user/addresses_controller.rb
> +  def show
Me parece uma boa validar se o usuario que esta vendo o endereço é 'dono' do endereço, o que acham?

2021-07-20 20:44 UTC, oliveira-matheus commented on app/controllers/user/addresses_controller.rb
> +    @addresses = Address.where(user: current_user)
Atualizado no commit 3201d26

2021-07-20 20:44 UTC, oliveira-matheus commented on app/controllers/user/addresses_controller.rb
> +    @address = Address.create(address_params.merge(user: current_user))
Atualizado no commit 3201d26

2021-07-20 20:49 UTC, oliveira-matheus commented on app/controllers/user/addresses_controller.rb
> +  def show
De acordo com o commit 3201d26, resolvemos manter a action show pois precisamos dela pra mostrar os endereços em detalhes. Para garantirmos a segurança, realizamos algumas modificações no controller para que o usuário consiga ver somente seus endereços. Adicionamos o teste 'can not access other user address' para garantir esse cenário.

2021-07-20 23:59 UTC, HenriqueMorato commented on Gemfile.lock
> +    brasil-estados (0.3.0)
Essa Gem está no Gemfile.lock mas não no Gemfile, acho que tem que atualizar o `bundler`

2021-07-20 23:59 UTC, HenriqueMorato commented on app/controllers/user/addresses_controller.rb
> +  def show
Será que na index não podemos ter os endereços completos e matar o show?

2021-07-21 19:22 UTC, oliveira-matheus commented on app/controllers/user/addresses_controller.rb
> +  def show
Removemos a action Show de acordo com o commit c8226bc

2021-07-21 19:22 UTC, oliveira-matheus commented on Gemfile.lock
> +    brasil-estados (0.3.0)
Como não estamos usando essa Gem, removemos ela no commit c8226bc

2021-07-22 18:53 UTC, joaorsalmeida approved these changes
Eu adicionaria um 'nome' ou 'título' ao endereço visto que o usuário pode ter vários. Mas isso pode vir em outro PR, o que acham?  Se concordarem lancem no backlog por favor.

2021-07-22 20:58 UTC, merged